CUDA: '2'
causal_layer: residual # null | adversarial | residual
aspect: abstract # abstract | structure | grammar_errors
cross_validation: False
cv_explanation: False
task: classification # classification | regression
folds: 10
lexicon_size: 150 # 50
on_validation_set: False # if True will not use test set
residual:
    epochs: 80
    batch_size: 500 #500 # 30
    lr: 0.0005 #0.0005# 0.0004
    hidden_dimensions:
        #- 64
        - 16
    lstm_hidden_dimension: 30 # 30 # 300 good performance bad conf on GRU # 120 # 500
    num_layers: 1  # Layers in the RN. Having more than 1 layer probably makes interpretability worst by combining more tokens into hiddent embs
    bidirectional: False
    cell_type: 'GRU' # 'GRU'
    causal_hidden_dimensions : 
        - 10 # 30
        - 5
    att_dim: 64
not_residual:
    epochs: 80 # 110
    batch_size: 500 # 150 # 30
    lr: 0.0005 # 0.0005
    hidden_dimensions:
        #this - 64 # 128 
        - 16 # 64  
    lstm_hidden_dimension: 30 # this 10 # 30 # 300 # 120 # 500
    num_layers: 1  # Layers in the RN. Having more than 1 layer probably makes interpretability worst by combining more tokens into hiddent embs
    bidirectional: False
    cell_type: 'GRU' # 'GRU'
    causal_hidden_dimensions : 
        - 128 # 300 [64]
        - 64 # 128
    att_dim: 64 #150
